# Generated by Django 5.0 on 2026-08-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_helpticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Anonymous', max_length=80)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('issue', models.CharField(choices=[('cant_login', "Can't log in to my account"), ('forgot_password', 'Forgot my password'), ('account_banned', 'My account was suspended/banned'), ('account_hacked', 'I think my account was hacked'), ('privacy_concern', 'Privacy or data concern'), ('report_user', 'Report a user / abusive content'), ('technical_issue', 'Technical / app issue'), ('feature_request', 'Feature request or feedback'), ('other', 'Other')], default='other', max_length=40)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
