# Generated by Django 5.0 on 2026-08-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ESCTRIX System Update', max_length=150)),
                ('message', models.TextField()),
                ('category', models.CharField(default='System Update', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
