# Generated by Django 5.0 on 2026-08-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_systembroadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='story_privacy',
            field=models.CharField(default='friends', max_length=20),
        ),
        migrations.AddField(
            model_name='userstory',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userstory',
            name='media_type',
            field=models.CharField(default='image', max_length=20),
        ),
        migrations.AddField(
            model_name='userstory',
            name='privacy',
            field=models.CharField(default='friends', max_length=20),
        ),
    ]
