# Generated by Django 5.0 on 2026-08-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username_last_changed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
