from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('auth/', views.auth_view, name='auth'),
    path('privacy/', views.privacy_policy_view, name='privacy'),
    path('terms/', views.terms_view, name='terms'),
    path('security/', views.security_view, name='security'),
    path('api/guest-contact/', views.api_guest_contact, name='api_guest_contact'),
    path('api/login/', views.api_login, name='api_login'),
    path('api/register/', views.api_register, name='api_register'),
    path('api/check-username/', views.api_check_username, name='api_check_username'),
    path('api/logout/', views.api_logout, name='api_logout'),
    path('api/search/', views.api_search, name='api_search'),
    path('api/friend-request/send/', views.api_send_friend_request, name='api_send_friend_request'),
    path('api/friend-request/cancel/', views.api_cancel_friend_request, name='api_cancel_friend_request'),
    path('api/friend-request/accept/', views.api_accept_friend_request, name='api_accept_friend_request'),
    path('api/friend-request/decline/', views.api_decline_friend_request, name='api_decline_friend_request'),
    path('api/friend/remove/', views.api_remove_friend, name='api_remove_friend'),
    path('api/friend-requests/pending/', views.api_pending_requests, name='api_pending_requests'),
    path('api/profile/update/', views.api_update_profile, name='api_update_profile'),
    path('api/profile/change-password/', views.api_change_password, name='api_change_password'),
    path('api/forgot-password/', views.api_forgot_password, name='api_forgot_password'),
    path('api/reset-password/', views.api_reset_password, name='api_reset_password'),
    path('api/help/submit/', views.api_submit_help_ticket, name='api_submit_help_ticket'),
    path('api/help/list/', views.api_get_help_tickets, name='api_get_help_tickets'),
    path('api/profile/get/', views.api_get_user_profile, name='api_get_user_profile'),
    path('api/block/add/', views.api_block_user, name='api_block_user'),
    path('api/block/remove/', views.api_unblock_user, name='api_unblock_user'),
    path('api/block/list/', views.api_block_list, name='api_block_list'),
    path('api/group/create/', views.api_create_group, name='api_create_group'),
    path('api/group/list/', views.api_group_list, name='api_group_list'),
    path('api/group/members/', views.api_group_members, name='api_group_members'),
    path('api/chat/history/', views.api_chat_history, name='api_chat_history'),
    path('api/group/history/', views.api_group_history, name='api_group_history'),
    path('api/story/create/', views.api_create_story, name='api_create_story'),
    path('api/story/list/', views.api_get_stories, name='api_get_stories'),
]
